[versions]

# /!\ Koin in gradle.properties /!\

# Core
kotlin = "2.0.21-KBA-010"
koin = "4.1.0"
koin-core-annotations = "4.1.0-kuikly-2.0.21-SNAPSHOT"
ksp = "2.0.21-1.0.28"
publish = "2.0.0"
dokka = "1.9.10"
nmcp = "1.0.1"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-annotations = { module = "io.insert-koin:koin-core-annotations", version.ref = "koin-core-annotations" }
ksp-api = {module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp"}

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nmcp = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
